package com.bloomtech.catsanddogs;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

// This is a Spring Boot Server application
// Spring Boot is a framework for managing a server application
// A framework is a set of classes to make common processing easier

// This is generated by teh Spring Initializr
// DO NOT CHANGE ANYTHING IN THIS CODE!

// Spring Boot uses a Tomcat Server with the name localhost and using port 8080
//
// Tomcat server is a free open source server from Apache used by many Java applications
// localhost - name used by any process running on your computer that take and handle requests
// a port is what an application listens for requests
//        think of a port as an apartment number in an apartment building
// localhost:8080  -->  localhost street, apt 8080



@SpringBootApplication   // This tells the server this is a Spring Boot Server application
public class Application
{
    // The start of the server occurs in main() method just like any other Java app
    public static void main(String[] args) {
        // Start the server for class specified and any args to pass to the server
        SpringApplication.run(Application.class, args);
    }

}
