package com.frank.server.server;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

// Generated by SpringInitialzr

@SpringBootApplication
public class SampleApiServerApplication {

	public static void main(String[] args) {
		SpringApplication.run(SampleApiServerApplication.class, args);
	}

}
